BondedECDSAKeepFactory implements IRandombeaconConsumer
It is to ensure the beacon callback function has a correct signature. If
it has not, the contract cannot be deployed:

```
Error:  *** Deployment Failed ***

"BondedECDSAKeepFactory" is an abstract contract or an interface and cannot be deployed.
   * Import abstractions into the '.sol' file that uses them instead of deploying them separately.
   * Contracts that inherit an abstraction must implement all its method signatures exactly.
   * A contract that only implements part of an inherited abstraction is
   also considered abstract.
```